import Head from 'next/head'
import { Roboto } from 'next/font/google'
import { Table } from '@/components/table'
import { useContext, useEffect } from 'react'
import { TitlePageContext } from '@/contexts/PageTitle'

export default function Home() {
  const { setTitlePage } = useContext(TitlePageContext);

  useEffect(() => {
    setTitlePage('');
  }, []);

  return (
    <>
      <Head>
        <title>Lista de arquivos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Table />
    </>
  )
}
