import Head from 'next/head'
import { Roboto } from 'next/font/google'
import { Container, Content } from '@/styles/index.styles'
import { Table } from '@/components/table'
import { ModalForm } from '@/components/modalForm'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Files</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className={`${roboto.className}`}>
        <h1>Lista de arquivos</h1>
        <Content>
          <ModalForm />
          <Table />
        </Content>
      </Container>
    </>
  )
}
